### ISSUE TITLE
Please archive

### ISSUE THREAD

**Issue by appetrosyan** [slowli/julia-set-rs#5]
This is not developed or maintained. Please make this a public archive

**Comment by slowli** [comment]
I have updated dependencies and clarified that the project is experimental (both in the readme and in the crate manifest) in #6. I've also configured Dependabot for the project so that dependencies don't get outdated in the future. If you have feature requests, improvement suggestions, bug reports etc., don't hesitate to submit them as new issues.

As a side note, since repository archival is a one-way action, I'd really hesitate to suggest it as a go-to solution for (seemingly) unmaintained code. I guess that's one of the reasons why there are a lot of GitHub repos that are not archived even though they don't have any activity for N years.
